# Generated by Django 5.1.3 on 2024-12-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='videocourse',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет (HEX-код)'),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет (HEX-код)'),
        ),
    ]
